# Generated by Django 2.2.3 on 2019-08-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('is_on', models.BooleanField(default=False)),
                ('brightness', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
