# Generated by Django 2.2.3 on 2019-08-01 10:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lamp',
            name='brightness',
            field=models.SmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='brightness %'),
        ),
    ]
