# Generated by Django 2.2.3 on 2019-08-03 08:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0002_brightness_range'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.SmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='brightness %')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('lamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lights.Lamp')),
            ],
        ),
    ]
