# Generated by Django 2.2.3 on 2019-08-03 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0003_add_workingperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingperiod',
            name='brightness',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='brightness %'),
        ),
    ]
