# Generated by Django 2.2.3 on 2019-08-03 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0004_fix_period_brightness'),
    ]

    operations = [
        migrations.AddField(
            model_name='lamp',
            name='last_switch',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
