# Generated by Django 2.2.3 on 2019-08-04 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lights', '0005_add_last_switch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingperiod',
            name='lamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', related_query_name='period', to='lights.Lamp'),
        ),
    ]
